### ISSUE TITLE
interface configuration should be possible on a per node basis

### ISSUE THREAD

**Issue by jan--f** [swiftgist/pillar-prototype#6]
As of now the interface definitions for the ceph.conf can be configured in srv/pillar/ceph/stack/defaults/ceph[-custom].yml. This means that all nodes will get the same configuration. This will make setups with heterogeneous hardware configurations hard.
I had problems with this when some of my VMs changed their interface name from eth0 to eth1 after a reboot.

**Comment by swiftgist** [comment]
You can create an exception per minion in the minions directory.  Ceph will still need the public and cluster networks to be consistent regardless of interface.  Since this is only used for creating ceph.conf and is specific to checking interfaces for monitors, I do not think many would assign a unique interface name to every minion.

This probably needs to be added as a documentation example though.  If one monitor had a bad NIC and your default is not 'eth0', the custom file could hold 'enp1s0' while mon2.ceph.yml contains 'enp3s0'.

**Comment by jan--f** [comment]
Ok that sounds exactly like what I had in mind. I guess the directory would be srv/pillar/ceph/stack/minions?

In any case, should we keep this issue around until this is properly documented?
I will also look into a reasonable error message, since the runner did not indicate any problems.

**Comment by swiftgist** [comment]
I have split the proposals for automation away from the actual pillar and stack now.  So, the same idea can still apply (i.e. customization can override default guesses) but we have a desire to get rid of the network interface and try to figure out the networks dynamically.  

I'm starting to think that allowing either since VM environments are typically consistent.

**Comment by jan--f** [comment]
Guess we don't use this anymore...closing.
